FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./apps/backend/package.json ./apps/backend/package.json

COPY ./turbo.json ./turbo.json


RUN bun install
RUN bun run db:generate

COPY . .

EXPOSE 8080

CMD ["bun", "run", "start:backend"]